dependencies:
- name: bdd-gh-1573296390
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-ghfjxy-import-1573298119
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-nh-1573296390
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-sbhg-1573296390
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-sbrp-import-1573298119
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-spring-1573295498
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.112
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.112
